FROM python:3.8.10-slim

WORKDIR /opt/app

RUN pip3 install iroha==1.0.0 ansible==2.10.7 && \
    pip3 uninstall -y protobuf && \
    pip3 install protobuf==3.12.2

COPY iroha_utils.py iroha_utils.py

ENTRYPOINT ["python3", "iroha_utils.py" ]