# tasks in this file check that role can be applied to hosts

- block:
  - name: check | check for deprecated variable
    fail:
      msg: "iroha_overlay_network is deprecated use: 'iroha_network'"
    when: iroha_overlay_network is defined
  - name:
    fail:
      msg: "'iroha_postgres_max_prepared_transactions' variable is depricated, use: 'iroha_postgres_commands'"
    when: iroha_postgres_max_prepared_transactions is defined
  - name: check | check iroha_hostnames length and iroha_replicas
    fail:
      msg: "'iroha_hostnames' length ({{ iroha_hostnames|length }}) should match the 'iroha_replicas' ({{ iroha_replicas }})"
    when: iroha_custom_hostnames and iroha_hostnames is defined and iroha_hostnames | length != iroha_replicas

  - name: check | check iroha_network
    fail:
      msg: "You can not use iroha_network == 'internal' if you have more than one host"
    when: iroha_network == 'internal' and ansible_play_hosts | length > 1

  - name: check | check postgres_docker_labels
    fail:
      msg: "postgres_docker_labels is deprecated use: 'iroha_postgres_docker_labels'"
    when: postgres_docker_labels  is defined

  - name: Check | Stop playbook if one host fail
    meta: end_play
    when: ansible_play_hosts_all != ansible_play_hosts

  tags: ["iroha-docker", "iroha-check"]
