- block:

  - name: Set iroha_command_host variable
    set_fact:
      iroha_command_host: "{% set output = {'host': inventory_hostname }  %}\
                              {% for key, value in hostvars.items() | sort %}\
                                 {% if value.iroha_service_host is defined and value.iroha_service_host %}\
                                   {% set _ = output.update({'host': key}) %}\
                                {% endif %}\
                              {% endfor %}\
                           {{ output.host }}"
    delegate_to: localhost
    run_once: yes
    become: no

  - name: Create deploy dir
    file:
      state: directory
      path: "{{ iroha_deploy_dir }}/conf"
    tags: ["iroha-docker", "iroha-util"]

  - name: Copy iroha-python util
    copy:
      src: "iroha_utils.py"
      dest: "{{ iroha_deploy_dir }}/iroha_utils.py"
    tags: ["iroha-docker", "iroha-util"]
    delegate_to: "{{ iroha_command_host }}"
    run_once: yes

  - name: Copy iroha-python util Dockerfile
    copy:
      src: "Dockerfile_iroha_python"
      dest: "{{ iroha_deploy_dir }}/Dockerfile_iroha_python"
    tags: ["iroha-docker", "iroha-util"]
    delegate_to: "{{ iroha_command_host }}"
    run_once: yes

  - name: Build docker image for iroha-python util
    docker_image:
      name: "{{ iroha_util_docker_image }}"
      build:
        path: "{{ iroha_deploy_dir }}"
        dockerfile: "Dockerfile_iroha_python"
        pull: yes
      source: build
      force_source: yes
    delegate_to: "{{ iroha_command_host }}"
    run_once: yes
    when: not iroha_util_custom_image
  tags: ["iroha-docker", "iroha-util"]