- name: Iroha check
  include_tasks: check.yml

- name: Iroha clean
  include_tasks: clean.yml

- name: Deploy Iroha util
  include_tasks: iroha-util.yml

- name: init Iroha vars
  include_tasks: init-vars.yml

- name: Migrate Rocksdb
  include_tasks: migrate-rocksdb.yml

- name: generate Iroha configs
  include_tasks: config-gen.yml

- name: deploy Iroha
  include_tasks: deploy.yml
