- name: Iroha check
  import_tasks: check.yml

- name: Iroha clean
  import_tasks: clean.yml

- name: Deploy Iroha util
  import_tasks: iroha-util.yml

- name: init Iroha vars
  import_tasks: init-vars.yml

- name: Migrate Rocksdb
  import_tasks: migrate-rocksdb.yml

- name: generate Iroha configs
  import_tasks: config-gen.yml

- name: deploy Iroha
  import_tasks: deploy.yml
