- name: Iroha check
  include: check.yml

- name: Iroha clean
  include: clean.yml

- name: init Iroha vars
  include: init-vars.yml

- name: Migrate rdb
  include: migrate-rdb.yml

- name: Deploy Iroha util
  include: iroha-util.yml

- name: generate Iroha configs
  include: config-gen.yml

- name: deploy Iroha
  include: deploy.yml
