- name: init vars
  include: init-vars.yml

- name: generate Iroha configs
  include: config-gen.yml

- name: deploy Iroha
  include: deploy.yml

- debug:
    msg: "Stop Iroha containers with `docker-compose -f {{ iroha_deploy_dir }}/docker-compose.yml down`"
  when: iroha_update_runtime_configs
  run_once: yes
