- name: stop Iroha
  docker_service:
    state: absent
    remove_volumes: yes
    project_src: "{{ iroha_deploy_dir }}"
  failed_when: False
  tags: ["iroha-docker"]

- name: delete deploy dir
  file:
    state: absent
    path: "{{ iroha_deploy_dir }}"
  tags: ["iroha-docker"]

- name: init vars
  include: init-vars.yml

- name: generate Iroha configs
  include: config-gen.yml

- name: deploy Iroha
  include: deploy.yml

- debug:
    msg: "Stop Iroha containers with `docker-compose -f {{ iroha_deploy_dir }}/docker-compose.yml down`"
  when: iroha_update_runtime_configs
  run_once: yes
