- name: Migrate rdb
  block:

    - name: Get postgres container info
      docker_container_info:
        name: "{{ iroha_inventory_human_hostname }}-postgres"
      register: _iroha_deploy_postgres_state


    - name: Check if postgres container is running
      assert:
        that: _iroha_deploy_postgres_state.container.State.Running and not _iroha_deploy_postgres_state.container.State.Restarting
        success_msg: "The container {{ iroha_inventory_human_hostname }}-postgres is running"
        fail_msg: "The container {{ iroha_inventory_human_hostname }}-postgres is not running"

    - name: Get iroha containers info
      docker_container_info:
        name: "{{ item.hostname[:item.hostname.rfind(':')] }}"
      register: _iroha_deploy_iroha_state
      loop: "{{ iroha_nodes }}"

    - name: Check if iroha containers are running
      assert:
        that: "{{ item.container.State.Running and not item.container.State.Restarting }}"
        success_msg: "The container {{ item.item.hostname[:item.item.hostname.rfind(':')] }} is running"
        fail_msg: "The container {{ item.item.hostname[:item.item.hostname.rfind(':')] }} is not running"
      loop: "{{ _iroha_deploy_iroha_state.results }}"

    - name: Check if new configuration is rdb
      fail:
        msg: "iroha_new_database_config and iroha_use_rdb should be True"
      when: "{{ not (iroha_new_database_config and iroha_use_rdb) }}"

    - name: Remove iroha containers
      docker_container:
        name: "{{ item.item.hostname[:item.item.hostname.rfind(':')] }}"
        state: absent
      loop: "{{ _iroha_deploy_iroha_state.results }}"

    - name: Configure docker compose template variables
      set_fact:
        _iroha_deploy_migration_container: True

    - name: Generate Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: "{{ iroha_deploy_dir }}/docker-compose.yml"

    - name: Generate config files
      template:
        src: config.docker.j2
        dest: "{{ iroha_deploy_dir }}/conf/{{ item.human_hostname }}/config.docker"
      loop: "{{ iroha_nodes }}"

    - name: Generate migration script
      template:
        src: migrate.sh.j2
        dest: "{{ iroha_deploy_dir }}/conf/{{ item.human_hostname }}/migrate.sh"
        mode: u=rwx,g=r,o=r
      loop: "{{ iroha_nodes }}"

    - name: Deploy temporary docker compose which runs the migration script
      docker_compose:
        project_src: "{{ iroha_deploy_dir }}"
        files:
        - docker-compose.yml
        state: present

    - name: Configure docker compose template variables
      set_fact:
        _iroha_deploy_migration_container: False

    - name: Remove postgres container
      docker_container:
        name: "{{ iroha_inventory_human_hostname }}-postgres"
        state: absent

  when: iroha_migrate_rdb is defined and iroha_migrate_rdb
  tags: ["iroha-migrate-rdb"]
