- name: Install packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - python-setuptools
    - python-pip
  when: ansible_python_version is search("^2\..*$")

- name: Install packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - python3-setuptools
    - python3-pip
  when: ansible_python_version is search("^3\..*$")

- name: Install docker python modules
  pip:
    name:
      - docker
      - docker-compose=={{ dockerComposeVersion }}
