- hosts: all
  # we need to use linear strategy, because some variables are set in runtime
  strategy: linear
  roles:
    - { role: iroha-docker, tags: iroha-docker }
  vars:
    iroha_docker_image: 'hyperledger/iroha'
    iroha_docker_tag: 'develop'